apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: rohith87/final_proj:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always  # Ensures the latest image is pulled
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort  # Use LoadBalancer if running in cloud (e.g., EKS, GKE)
  selector:
    app: react-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # Optional: Set a static port or let Kubernetes assign one
